version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    build: ./src/Api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TasksDb;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - api
